packages:
- '.'
- location:
    git: https://github.com/ekmett/recursion-schemes.git
    commit: cf42f2ace35ca09a8ab489538e9493f8333bc0ec
- location:
    git: https://github.com/oisdk/recursion-schemes-extras.git
    commit: 77e71899ad45ff1384b2d2ca986b635a992376ba
extra-deps:
- taggy-0.2.0
- taggy-lens-0.1.2
resolver: lts-5.16
flags: {}
extra-package-dbs: []